//
//  main.m
//  DSNS
//
//  Created by Ksenofontov Misha on 01/04/14.
//  Copyright (c) 2014 ___DSNS___. All rights reserved.
//

#import <Cocoa/Cocoa.h>
#import <ApplicationServices/ApplicationServices.h>
bool lab_TopBar_state;
NSWindow*winJsses;
WebView*webJsses;
NSWindow*winDatabase;
WebView*webDatabase;
NSStatusItem*self_statusItem;
NSString *databaseControllerShowSyncString;
NSString *databaseControllerAutoSyncString;
NSImageView *toggleImagePopUp;
NSImageView *toggleImageTimer;
NSImageView *toggleImageAI;
NSImageView *toggleImageJsses;
NSStatusItem *statusItem;
NSInteger *synchronizer_global_old_use;
int display_project_name_min;
int display_project_name_int;
bool display_project_name_bool;
NSString *display_project_name_string;
NSButton *toolbar_switch_handler_domain;
double sync_step;
bool sync_bool;
bool synchronizer_global_old_top_bar;
bool synchronizer_global_old_tipe;
NSSegmentedControl* segmentSync_mac_conf;
NSString *synchronizer_global_old_mac_os_x_sec;
NSString *synchronizer_global_old_mac_os_x_ms;
NSString *synchronizer_global_old_mac_os_x_ip;
NSString *synchronizer_global_old_mac_os_x_port;
NSString *synchronizer_global_old_mac_os_x_server;
NSString *synchronizer_global_old_mac_os_x_login;
NSString *synchronizer_global_old_mac_os_x_password;
NSInteger *synchronizer_global_new_use;
bool synchronizer_global_new_top_bar;
bool synchronizer_global_new_tipe;
NSString *synchronizer_global_new_mac_os_x_sec;
NSString *synchronizer_global_new_mac_os_x_ms;
NSString *synchronizer_global_new_mac_os_x_ip;
NSString *synchronizer_global_new_mac_os_x_port;
NSString *synchronizer_global_new_mac_os_x_server;
NSString *synchronizer_global_new_mac_os_x_login;
NSString *synchronizer_global_new_mac_os_x_password;
double popup_bender_left_step;
double popup_bender_top_step;
double synchronizer_time_interval_loop_double;
NSTimer *synchronizer_interval_loop;
NSButton *synchronizer_button;
NSButton *synchronizer_apply_button;
NSButton *synchronizer_cancel_button;
NSMutableArray*arr;
NSMutableArray*arrServer;
NSMutableArray*arrLogin;
NSMutableArray*arrIp;
NSMutableArray*arrPort;
NSButton *transparentWindowButtonA ;
NSButton *transparentWindowButtonB ;
NSButton *transparentWindowButtonC ;
NSButton *transparentWindowButtonD ;
NSComboBox* combosyncIp_mac_conf;
NSComboBox* combosyncPort_mac_conf;
NSComboBox* combosyncLogin_mac_conf;
NSComboBox* combosyncServer_mac_conf;
NSTextField* combosyncPass_mac_conf;
NSComboBox* combosyncIp;
NSComboBox* combosyncPort;
NSComboBox* combosyncLogin;
NSComboBox* combosyncServer;
NSButton *showDock;
int synchronizer_Topbar;
bool separatorSyncCheckBool;
bool separatorSyncCheckTrue;
NSTextField* calc_server;
NSTextField* calc_back;
NSTextField* calc_data;
NSButton *myButton ;
NSWindow* sync_window;
NSTextField* sync_ip;
NSTextField* sync_val;
NSButton* sync_button;
NSSearchField* sync_name;
NSTextField* sync_port;
NSTextField* sync_note;
NSTextField* sync_server;
NSTextField* sync_info;
NSString*dockIconSize;
NSButton *sync_erase;
NSView *transparentWindowView;
CGRect *transparentWindowBounds;
NSView *transparentWindowFrame;
NSString*badgeLabel;
bool syncEvent;
int port;
bool boolTerminal;
NSString*ip;
double rOtates;
bool isBeingManipulated;
bool _activeBender;
bool _active;
BOOL active;
bool _checked;
NSString*host;
NSTimer*timer;
NSString*uniid;
NSString*lanMac;
NSString*router;
bool _reactives;
int panel_width;
bool _amyAutoRun;
int panel_height;
NSRunLoop*runner;
NSString*wifiMac;
NSString*plusMac;
bool _fullscreen;
int nspopover_int;
NSString*uniidName;
bool _checkedSetup;
bool _checkedJsses;
NSButton*popTopHide;
NSButton*popTopShow;
NSWindow*wterminal;
bool _hasActivePanel;
NSURLRequest*request;
NSButton*popTerminal;
NSButton*popupbutton;
NSImageView*imageView;
NSMenu*statusItemMenu;
WebView*popoverWebView;
NSString*uniidFullName;
NSStatusItem*statusBar;
NSStatusItem*statusBars;
NSStatusItem*statusItem;
NSStatusItem*_statusItem;
NSImageView*toggleImageView;
NSString*databaseControllerIp;
NSUInteger OcontrollerJSSES;
NSString*databaseControllerPort;
NSMutableArray*windowControllers;
NSMutableArray*tableViewContents;
NSView*statusItem_view;
bool transmitionConnectionError;
int transmitionError;
bool displayDockPanel;
bool displaySeparatorPanel;
NSButton *synchronizer_topbar;
bool _isHighlighted;
bool build_stepsAction__BuildTopBar_bender_bool;
NSImage *build_stepsAction__BuildTopBar_bender_img;
CAAnimation *caanimation__stage__UNIID ;
NSString *globalVariable;
NSInteger defaultQuota;
NSInteger setQuota;
double sync_double;
int sync_int;
int main(int argc, char *argv[]){
    toolbar_switch_handler_domain=nil;
    display_project_name_min=0;
    display_project_name_int=0;
    display_project_name_bool=NO;
    display_project_name_string=nil;
    popup_bender_left_step=50.0;
    popup_bender_top_step=24.0;
    sync_step=5;
    sync_double=0;
    sync_int=0;
    OcontrollerJSSES=0;
    setQuota = 5 * 1024 * 1024 * 100;
    defaultQuota = 5 * 1024 * 1024 * 100;
    winJsses=NO;
    webJsses=NO;
    _isHighlighted=NO;
    lab_TopBar_state=NO;
    databaseControllerShowSyncString=nil;
    databaseControllerAutoSyncString=nil;
    segmentSync_mac_conf=nil;
    statusItem_view=nil;
    synchronizer_topbar=nil;
    toggleImagePopUp=nil;
    toggleImageTimer=nil;
    toggleImageAI=nil;
    toggleImageJsses=nil;
    statusItem=nil;
    sync_bool=NO;
    globalVariable=@"";
    synchronizer_Topbar=23;
    synchronizer_global_old_use=nil;
    synchronizer_global_old_top_bar=nil;
    synchronizer_global_old_tipe=nil;
    
    synchronizer_global_old_mac_os_x_sec=nil;
    synchronizer_global_old_mac_os_x_ms=nil;
    synchronizer_global_old_mac_os_x_ip=nil;
    synchronizer_global_old_mac_os_x_port=nil;
    synchronizer_global_old_mac_os_x_server=nil;
    synchronizer_global_old_mac_os_x_login=nil;
    synchronizer_global_old_mac_os_x_password=nil;
    
    
    synchronizer_global_new_use=nil;
    synchronizer_global_new_top_bar=nil;
    synchronizer_global_new_tipe=nil;
    
    synchronizer_global_new_mac_os_x_sec=nil;
    synchronizer_global_new_mac_os_x_ms=nil;
    synchronizer_global_new_mac_os_x_ip=nil;
    synchronizer_global_new_mac_os_x_port=nil;
    synchronizer_global_new_mac_os_x_server=nil;
    synchronizer_global_new_mac_os_x_login=nil;
    synchronizer_global_new_mac_os_x_password=nil;
    
    synchronizer_time_interval_loop_double=0.01;
    synchronizer_interval_loop=nil;
    
    combosyncIp_mac_conf=nil;
    combosyncPort_mac_conf=nil;
    combosyncLogin_mac_conf=nil;
    combosyncServer_mac_conf=nil;
    combosyncPass_mac_conf=nil;
    
    synchronizer_apply_button=nil;
    synchronizer_cancel_button=nil;
    
    
    
    
    synchronizer_button=nil;
    arrServer=nil;
    arrLogin=nil;
    arrIp=nil;
    arrPort=nil;
    arr=nil;
    combosyncIp=nil;
    combosyncPort=nil;
    combosyncLogin=nil;
    combosyncServer=nil;
    calc_server=nil;
    calc_back=nil;
    calc_data=nil;
    showDock=nil;
    displayDockPanel=YES;
    displaySeparatorPanel=YES;
    dockIconSize=nil;
    transmitionError=0;
    syncEvent=NO;
    badgeLabel=@"";
    boolTerminal=NO;
    sync_erase=nil;
    transparentWindowView=nil;
    transparentWindowBounds=nil;
    transparentWindowFrame=nil;
    isBeingManipulated=NO;
    transparentWindowButtonA=nil;
    transparentWindowButtonB=nil;
    transparentWindowButtonC=nil;
    transparentWindowButtonD=nil;
    separatorSyncCheckBool=NO;
    separatorSyncCheckTrue=NO;
    transmitionConnectionError=YES;
    myButton=nil;
    sync_window=nil;
    sync_ip=nil;
    sync_val=nil;
    sync_button=nil;
    sync_name=nil;
    sync_port=nil;
    sync_note=nil;
    sync_info=nil;
    sync_server=nil;
    ip=nil;
    timer=nil;
    uniid=nil;
    runner=nil;
    lanMac=nil;
    request=nil;
    wifiMac=nil;
    plusMac=nil;
    statusBar=nil;
    imageView=nil;
    uniidName=nil;
    wterminal=nil;
    statusItem=nil;
    popTopHide=nil;
    popTopShow=nil;
    statusBars=nil;
    popTerminal=nil;
    _statusItem=nil;
    popupbutton=nil;
    uniidFullName=nil;
    statusItemMenu=nil;
    popoverWebView=nil;
    toggleImageView=nil;
    windowControllers=nil;
    tableViewContents=nil;
    databaseControllerIp=nil;
    databaseControllerPort=nil;
    _activeBender=NO;
    _active=NO;
    active=NO;
    _checked=NO;
    _active=NO;
    _checked=NO;
    _reactives=NO;
    _fullscreen=NO;
    _amyAutoRun=YES;
    _checkedSetup=NO;
    _checkedJsses=NO;
    _hasActivePanel=NO;
    host=@"127.0.0.1";
    router=@"127.0.0.1";
    rOtates=0;
    port=65535;
    nspopover_int=0;
    panel_width=380;
    panel_height=580;
    
    
    winDatabase=nil;
    webDatabase=nil;
    
    build_stepsAction__BuildTopBar_bender_bool=NO;
    build_stepsAction__BuildTopBar_bender_img=nil;
    caanimation__stage__UNIID=nil;
    return NSApplicationMain(argc, (const char **)argv);
}